---
version: "3"

services:
        flask-app:
                build:
                        context: ./
                        dockerfile: ./Dockerfile
                ports: 
                      - 5000:5000        
                image: jetp104/iss_tracker:midterm
                #volumes:
                #     - ./config.yaml:/config.yaml
